### ISSUE TITLE
cp-ksql-cli floods stdout with null pointer exceptions on startup with k8s.

### ISSUE THREAD

**Issue by sinplea** [confluentinc/ksql#1631]
I am trying to deploy a small developer instance of the new 4.1.2 docker images of ksql on kubernetes. The CLI works when I exec into the container. I can run the KSQL command, connect to the server, and run queries; but when checking the logs upon startup, this message floods into our log aggregator by the thousands.

```
ksql> java.lang.NullPointerException
```

There is no error at the beginning of the logs that indicate what is causing the null pointer exception, but I can guarentee it happens at startup. Any help would be much appreciated.

Here is my deployment yaml:

```yaml
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ksql
  namespace: kafka
  labels:
    app: kafka-ksql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ksql
  template:
    metadata:
      labels:
        app: kafka-ksql
    spec:
      containers:
      - name: kafka-ksql-server
        image: confluentinc/cp-ksql-server:4.1.2
        ports:
        - containerPort: 8088
        env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: bootstrap:9092
        - name: KSQL_LISTENERS
          value: http://0.0.0.0:8088
        - name: KSQL_KSQL_SERVICE_ID
          value: setup_1
        - name: KSQL_OPTS
          value: -Dksql.schema.registry.url=http://cp-schema-registry:8081
      - name: kafka-ksql-cli
        image: confluentinc/cp-ksql-cli:4.1.2
        ports:
        - containerPort: 8087
        env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: bootstrap:9092
        - name: KSQL_OPTS
          value: -Dksql.service.id=setup_1 -Dlisteners=http://0.0.0.0:8088/
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-ksql
  namespace: kafka
  labels:
    app: kafka-ksql
spec:
  selector:
    app: kafka-ksql
  ports:
  - name: cp
    port: 8088
```

**Comment by apurvam** [comment]
Is the `cp-ksql-cli` being run as a daemon? It is intended to only be run in interactive mode.

**Comment by apurvam** [comment]
closing this out due to a lack of activity.

**Comment by jcasstevens** [comment]
I experience this as well when trying to run both `cp-ksql-server:5.0.0-1 `and `cp-ksql-cli:5.0.0-1` through docker-compose.

in my `docker-compose.yml`:
```
  ksql-server-interactive:
   image: confluentinc/cp-ksql-server:5.0.0-1
   hostname: ksql-server-interactive
   container_name: ksql-server-interactive
   depends_on:
     - kafka
     - connect
     - schema-registry
   ports:
     - "8088:8088"
   environment:
     KSQL_CONFIG_DIR: "/etc/ksql"
     KSQL_KSQL_EXTENTION_DIR: "/usr/ext"
     KSQL_LISTENERS: "http://0.0.0.0:8088"
     KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
     KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
     KSQL_HOST_NAME: ksql-server-interactive
     KSQL_APPLICATION_ID: "dev-test"
     KSQL_CACHE_MAX_BYTES_BUFFERING: 0
     KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
     KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
     KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"

  ksql-cli:
    image: confluentinc/cp-ksql-cli:5.0.0-1
    hostname: ksql-cli
    container_name: ksql-cli
    depends_on:
      - kafka
      - connect
      - ksql-server-interactive
      - schema-registry
```

My ksql-cli behaves as expected, I can connect to my ksql-server service, run queries, etc.. However when I check the `docker logs` for the ksql-cli, it has thousands of `ksql> java.lang.NullPointerException` errors. Am I missing something in my configuration by chance?
