### ISSUE TITLE
My custom UDF is not showing up after ksql-server restart

### ISSUE THREAD

**Issue by asifakb** [confluentinc/ksql#1794]
Team,

I'm using cp_all_in_one docker images for my work and I see that new UDF that I created is not showing up after copying of the jar and deploying in the ksql-server. Here is my UDF class

```java
package asifakb.kafka.streams.machinelearning;

import io.confluent.ksql.function.udf.Udf;
import io.confluent.ksql.function.udf.UdfDescription;

@UdfDescription(name = "sigmoid", description = "computes the sigmoid function")
public class Sigmoid {

    @Udf(description = "computes sigmoid for a given double type")
    public static double sigmoid(double t) {
        System.out.println("Sigmoid: UDF starting");
        return 1 / (1 + Math.pow(Math.E, (-1 * t)));
    }
}
```

I have updated my docker-compose.yml with new property called KSQL_EXT_DIR to hold the path value

```
 ksql-server:
    image: confluentinc/cp-ksql-server:latest
    networks:
      - confluent
    hostname: ksql-server
    container_name: ksql-server
    depends_on:
      - broker
      - connect
    ports:
      - "8088:8088"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      **KSQL_EXT_DIR: "/etc/ksql-server/ext"**
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
      KSQL_BOOTSTRAP_SERVERS: "broker:9092"
      KSQL_HOST_NAME: ksql-server
      KSQL_APPLICATION_ID: "cp-all-in-one"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
```

ISSUE #1:  The uber.jar with all dependencies was copied at ksql-server's path '/etc/ksql-server/ext' folder. First of all , I need to know if this is the right path for ksql docker image because the documentation supplied for creating UDF do not explicitly or clearly explain which location of docker image this jar need to be bundled?

ISSUE #2: During the start-up the config entry is being picked up but NO MESSAGE was displayed in logs saying that so and so jar has been found and UDF is successfully loaded or parsed....an acknowledgement is missing 

ISSUE #3: ksql > show functions or LIST functions do not display new UDF method that was added....

Can you please help us
