### ISSUE TITLE
[cp-ksql-cli] Error at start: java.lang.NullPointerException

### ISSUE THREAD

**Issue by sneko** [confluentinc/ksql#1874]
Hi,

I already deployed cp-ksql-server in my Kubernetes but I still get an error when deploying my cp-ksql-cli... Here is the deployment.yaml I'm using:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ksql-cli
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: ksql-cli
    spec:
      containers:
      - name: ksql-cli
        image: confluentinc/cp-ksql-cli:latest
        imagePullPolicy: Always
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
```

_Note: The part with "XXX" is what I will show below since I made different tries_

The error I always get is:
```
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
ksql&gt; java.lang.NullPointerException
...
```

Here are some tries I made:
```
        command: ["ksql"]
        args: ["http://myhostname:8088"]
```

```
        command: ["/usr/bin/ksql"]
        args: ["http://myhostname:8088"]
```

```
        command:
        - "/bin/bash"
        - "-c"
        - "ksql http://myhostname:8088"
```

I also tried just with the args variable since the ENTRYPOINT is already "ksql" (https://github.com/confluentinc/ksql/blob/4.1.x/cp-ksql-cli/Dockerfile#L30):
```
        args: ["http://myhostname:8088"]
```

But none of them work, I always get the error 😭 

What's weird is when I connect to my pod directly and that I execute `ksql http://myhostname:8088`, it works like a charm!

I don't understand why at startup the pod can't handle what I'm giving to it, but behaves differently when that's not the pod starting.

I guess I make an error with my startup settings but for me:
- Kubernetes command = Dockerfile ENTRYPOINT
- Kubernetes arg = Dockerfile CMD

Anyone could help me please?

Thank you,
