### ISSUE TITLE
Unable to run KSQL-Server Docker container in headless mode

### ISSUE THREAD

**Issue by jcasstevens** [confluentinc/ksql#1963]
We've been running the entire CP platform in docker-compose as we test/develop, using both the KSQL-Server and the KSQL-CLI to develop our streams and ksql statements. We are now trying to convert our KSQL-server instance to run in headless mode using the same ksql statements we've been testing through the CLI.

Upon bring up the docker-compose file when our `streams.sql` file has statements in it, the ksql-server service consistently crashes with an exit 255 state, with zero output indicating why it failed.

If we empty the contents of our `streams.sql` file and try to bring up the compose file, ksql-server is up and running just fine in headless mode.

Below is our configuration for our ksql-server service:

```
ksql-server:
    image: confluentinc/cp-ksql-server:5.0.0-1
    hostname: ksql-server
    container_name: ksql-server
    depends_on:
      - kafka
      - connect
      - schema-registry
    ports:
      - "8088:8088"
    volumes:
      - ./../kafka-utils/:/usr/ext #mounts a custom UDF jar for ksql
      - ./../kafka-ksql/statements/:/etc/ksql/queries #mounts our .sql file for ksql queries file
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_KSQL_EXTENTION_DIR: "/usr/ext"
      KSQL_KSQL_QUERIES_FILE: /etc/ksql/queries/streams.sql
      KSQL_KSQL_SERVICE_ID: "ksql_standalone_"
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
      KSQL_HOST_NAME: ksql-server
      KSQL_APPLICATION_ID: "dev"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
```

I've compared our `streams.sql` file to that of https://github.com/rmoff/ksql/blob/clickstream-c3/ksql-clickstream-demo/docker-compose.yml#L100 and the syntax matches identically.
Even though our statements work just fine via the CLI, we've tried just a very simple CREATE TABLE statement with no comments in our .sql file, and experience the same result.

Are missing any configurations here, or is this a bug when running in docker?
