### ISSUE TITLE
Server v<unknown> located at http://localhost:8088

### ISSUE THREAD

**Issue by robincvlr** [confluentinc/ksql#2126]
Hi everybody, 

I try to use ksql-server and ksql-cli to query my Kafka messages with the following `docker-compose.yml ` : 
```
ksql-server:
    image: confluentinc/cp-ksql-server
    container_name: ksql-server
    depends_on:
      - kafka
    ports:
      - "8088:8088"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
      KSQL_APPLICATION_ID: "villo"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_AUTO_OFFSET_RESET: "earliest"
      KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
    networks:
      - confluent

  ksql-cli:
    image: confluentinc/cp-ksql-cli
    depends_on:
      - kafka
    environment:
      KSQL_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      KSQL_LISTENERS: PLAINTEXT://ksql-server:8088
    networks:
      - confluent
    entrypoint: /bin/sh
    tty: true
    stdin_open: true
```
When I attach my ksql-cli docker to launch KSQL, I read the following sentence : 
```
CLI v5.0.0, Server v<unknown> located at http://localhost:8088
Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!
**************** ERROR ********************
Remote server address may not be valid.
Address: http://localhost:8088
Error issuing GET to KSQL server
Caused by: java.net.ConnectException: Connection refused (Connection refused)
Caused by: Could not connect to the server.
*******************************************
```
The `docker logs` command line for ksql-server docker gives me a warning : 
`WARNING: A provider io.confluent.ksql.rest.server.resources.KsqlResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider io.confluent.ksql.rest.server.resources.KsqlResource will be ignored. `
Is this related to my issue ? 
I would like to know what goes wrong in my docker composition. I opened my port and succeed my message streaming through the Kafka / Zookeeper / Kafka Connect stack. 
 
Thank you in advance for your interest.
