### ISSUE TITLE
KSQL cannot connect to AVRO

### ISSUE THREAD

**Issue by lozuwa** [confluentinc/ksql#2321]
Hello, I am having a problem connecting KSQL and schema-registry through docker. 

<b>OS:</b> CentOS 7
<b>Orchestrator:</b> docker-compose
<b>Instructions:</b>
<ul>
<li>1. Start docker-compose: </li>
</ul>

Note the MY-IP-ADDRESS listener
```yml
version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
    - 2181:2181
    restart: always

  kafka:
    image: wurstmeister/kafka:latest
    ports:
    - 9092:9092
    links:
    - zookeeper
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /data/zebra/mwe/3rdParty/kafka:/kafka
    - /var/log/zebra/mwe/kafka-logs:/opt/kafka/logs
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=MY-IP-ADDRESS
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_CREATE_TOPICS=topic_test:1:1
    - KAFKA_DELETE_TOPIC_ENABLE=true
    - KAFKA_DATA_DIRS=/kafka
    - KAFKA_LOG_RETENTION_BYTES=5000000000
    - "xpack.security.enabled=false"
    - "xpack.monitoring.enabled=true"
    depends_on:
    - zookeeper
    restart: always

  ksqlserver:
    image: confluentinc/cp-ksql-server:latest
    ports:
      - 9088:8088
    environment:
      - KSQL_BOOTSTRAP_SERVERS=http://kafka:9092
      - KSQL_LISTENERS=http://0.0.0.0:8088
      - KSQL_SCHEMA_REGISTRY_URL=http://schema-registry:8081
    volumes:
      - /data/zebra/mwe/3rdParty/ksql:/var/local
    depends_on:
      - kafka
    restart: always

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
    restart: always
```

<ul>
<li>2. Run KSQL-CLI</li>
</ul>
docker run --rm --interactive --tty confluentinc/cp-ksql-cli:5.0.0 http://MY-IP-ADDRESS:9088
<br>

<br>
<ul>
<li>3. Create a STREAM based on the topic. </li>
</ul>
CREATE STREAM dummy_stream WITH (kafka_topic='topic_test', value_format='AVRO');
<br>

<br>
<ul>
<li>4. ERROR:</li>
</ul>
Unable to verify if the Avro schema for topic mwe.resource.locate is compatible with KSQL.
Reason: Connection refused (Connection refused)

Please see https://github.com/confluentinc/ksql/issues/ to see if this particular reason is already
known, and if not log a new issue. Please include the full Avro schema that you are trying to use.

<br>
What could be the problem? Thanks
