### ISSUE TITLE
cannot run client-server mode with docker-compose

### ISSUE THREAD

**Issue by xmlking** [confluentinc/ksql#275]
I have few issues running  `ksql-server-start`   in Docker Env.
1. First argument is mandatory  i.e., `ksql-server-start /etc/ksql/ksqlserver.properties`  
It should be optional and  if not supplied, should use default file based on `KSQL_CONFIG_DIR`  Environment variable.  
2.  We should be able to provide  `bootstrap.servers` property via Environment variable.  `STREAMS_BOOTSTRAP_SERVERS` has no effect.   

  inconsistent with statement at   https://github.com/confluentinc/ksql/blob/master/docs/concepts.md 
> Use with default settings:
```bash
  ./bin/ksql-server-start
```

#### Test docker-compose.yml
 
```yml
version: '2.1'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper:/var/lib/zookeeper
    networks:
      - reactive-network

  kafka:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - kafka:/var/lib/kafka
    networks:
      - reactive-network
    links:
      - zookeeper
    depends_on:
      - zookeeper

  ksql-server:
    image: confluentinc/ksql-cli
    ports:
      - 9098:8080
    networks:
      - reactive-network
    links:
      - kafka
    depends_on:
      - kafka
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      STREAMS_BOOTSTRAP_SERVERS: kafka:9092
    entrypoint: 'ksql-server-start /etc/ksql/ksqlserver.properties'

networks:
  reactive-network:
    driver: bridge

volumes:
  zookeeper:
  kafka:
```
