### ISSUE TITLE
ksqlDB spams window end warnings with bulk inserts

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#4925]
**Describe the bug**

I was getting ready to release a new version of my connector, Voluble, and noticed that ksqlDB 0.8.0 is now spamming a warning that wasn't present in previous releases of ksqlDB.

**To Reproduce**

Download the Voluble connector and put it in a directory called voluble:

```
confluent-hub install mdrogalis/voluble:0.2.0
```

Then start up the following with Docker Compose:

```
---
version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-enterprise-kafka:5.4.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.8.0
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - broker
    ports:
      - "8088:8088"
    volumes:
      - "./voluble/:/usr/share/kafka/plugins/voluble"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: broker:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_CONNECT_GROUP_ID: "ksql-connect-cluster"
      KSQL_CONNECT_BOOTSTRAP_SERVERS: "broker:9092"
      KSQL_CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      KSQL_CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      KSQL_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      KSQL_CONNECT_CONFIG_STORAGE_TOPIC: "ksql-connect-configs"
      KSQL_CONNECT_OFFSET_STORAGE_TOPIC: "ksql-connect-offsets"
      KSQL_CONNECT_STATUS_STORAGE_TOPIC: "ksql-connect-statuses"
      KSQL_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_PLUGIN_PATH: "/usr/share/kafka/plugins"

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.8.0
    container_name: ksqldb-cli
    depends_on:
      - broker
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true
```

Then go into the CLI:

```
docker exec -it ksqldb-cli ksql http://ksqldb-server:8088
```

And run a simple connector configuration. This one just makes one topic named 'customers' with a string key and a value with a map `name` of type string. New records are produced every 500 ms:

```
CREATE SOURCE CONNECTOR customers WITH (
    'connector.class' = 'io.mdrogalis.voluble.VolubleSourceConnector',
    'genkp.customers.with' = '#{Internet.uuid}',
    'genv.customers.name.with' = '#{HitchhikersGuideToTheGalaxy.character}',
    'global.throttle.ms' = '500'
);
```

Everything is fine until this point. If I do `print 'customers' from beginning;`, though, the logs for ksqlDB server spam with this:

```
[2020-03-28 22:17:57,865] INFO Printing topic 'customers' (io.confluent.ksql.rest.server.resources.streaming.StreamedQueryResource:359)
[2020-03-28 22:17:58,077] WARN Warning: window end time was truncated to Long.MAX (org.apache.kafka.streams.state.internals.WindowKeySchema:109)
[2020-03-28 22:17:58,078] WARN Warning: window end time was truncated to Long.MAX (org.apache.kafka.streams.state.internals.WindowKeySchema:109)
[2020-03-28 22:17:58,565] WARN Warning: window end time was truncated to Long.MAX (org.apache.kafka.streams.state.internals.WindowKeySchema:109)
[repeated ...]
```

If I kill the print, the warnings still continue. If I drop the connector, they stop. If I then reprint the topic, they start again until all records have been printed.

**Expected behavior**

Warnings shouldn't spam in the logs. If the message is legitimate (I suspect it's not since this wasn't in previous versions, and the data isn't windowed), we should throttle the rate of the warnings.
