### ISSUE TITLE
Unable to start ksqlDB, 

### ISSUE THREAD

**Issue by shekp** [confluentinc/ksql#5116]
Hello, 

Could you please help, I am trying to install and start ksqlDB using docker-compose with already installed **Apache Kafka version 2.11**

Apache Kafka uses SASL PLAIN mechanism.

This is my docker-compose.yml file content:

```

version: '2'

services:
  ksqldb-server:
    image: confluentinc/ksqldb-server:0.8.1
    hostname: ksqldb-server
    container_name: ksqldb-server
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: "10.10.10.10:9092"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
      KSQL_SASL_MECHANISM: "PLAIN"
      KSQL_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\" password=\"password\";"
  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.8.1
    container_name: ksqldb-cli
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true
```

After starting with command - docker-compose up, I am faced with message

`ksqldb-server    | [2020-04-20 13:51:06,507] WARN The configuration 'sasl.jaas.config' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:355)
ksqldb-server    | [2020-04-20 13:51:06,507] WARN The configuration 'sasl.jaas.config' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:355)
ksqldb-server    | [2020-04-20 13:51:07,450] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:63)
ksqldb-server    | io.confluent.ksql.util.KsqlServerException: Could not get Kafka authorized operations!
ksqldb-server    | 	at io.confluent.ksql.services.KafkaClusterUtil.isAuthorizedOperationsSupported(KafkaClusterUtil.java:54)
ksqldb-server    | 	at io.confluent.ksql.security.KsqlAuthorizationValidatorFactory.create(KsqlAuthorizationValidatorFactory.java:52)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:711)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:629)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:101)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:59)
ksqldb-server    | Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnsupportedVersionException: Attempted to write a non-default includeClusterAuthorizedOperations at version 7
ksqldb-server    | 	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
ksqldb-server    | 	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
ksqldb-server    | 	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
ksqldb-server    | 	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
ksqldb-server    | 	at io.confluent.ksql.services.KafkaClusterUtil.isAuthorizedOperationsSupported(KafkaClusterUtil.java:52)
ksqldb-server    | 	... 5 more
ksqldb-server    | Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: Attempted to write a non-default includeClusterAuthorizedOperations at version 7`
