### ISSUE TITLE
Quickstart existing broker example does not work for 0.14.0

### ISSUE THREAD

**Issue by joekrie** [confluentinc/ksql#6914]
**Describe the bug**
For ksqlDB 0.14.0, when following the [Quickstart](https://ksqldb.io/quickstart.html) standalone Docker example for an existing broker, I get the error `Failed to handle: Command{statement='CREATE STREAM KSQL_PROCESSING_LOG...`. The example does work if I use ksqlDB 0.10.0 instead. The error happens when trying to create the processing log stream.

**To Reproduce**
1. Go to the [Quickstart](https://ksqldb.io/quickstart.html), choose "Standalone", then "My Kafka broker is running elsewhere".
2. Add bootstrap server URLs, then copy text into docker-compose.yaml file. It will look like this:
```
---
version: '2'

services:
  ksqldb-server:
    image: confluentinc/ksqldb-server:0.14.0
    hostname: ksqldb-server
    container_name: ksqldb-server
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: *****
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.14.0
    container_name: ksqldb-cli
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true
```
3. Run `docker compose up`

**Expected behavior**
ksqlDB server should start up and create the processing log stream.

**Actual behaviour**
The step to create the processing log stream errors out, and it keeps trying and failing to create the stream.
```
ksqldb-server    | [2021-01-28 18:25:55,779] ERROR Failed to handle: Command{statement='CREATE STREAM KSQL_PROCESSING_LOG
ksqldb-server    | (LOGGER STRING, LEVEL STRING, `TIME` BIGINT, MESSAGE STRUCT<`type` INTEGER, deserializationError STRUCT<errorMessage STRING, recordB64 STRING>, recordProcessingError STRUCT<errorMessage STRING, record STRING>, productionError STRUCT<errorMessage STRING>>) WITH (KAFKA_TOPIC='default_ksql_processing_log', VALUE_FORMAT='JSON');', overwriteProperties={}, version=Optional.empty} (io.confluent.ksql.rest.server.computation.InteractiveStatementExecutor:214)
ksqldb-server    | io.confluent.ksql.util.KsqlException: This version of ksqlDB does not support executing statements submitted prior to ksqlDB 0.8.0 or Confluent Platform ksqlDB 5.0. Please see the upgrading guide to upgrade.
ksqldb-server    |      at io.confluent.ksql.rest.server.computation.InteractiveStatementExecutor.throwUnsupportedStatementError(InteractiveStatementExecutor.java:309)
ksqldb-server    |      at io.confluent.ksql.rest.server.computation.InteractiveStatementExecutor.executeStatement(InteractiveStatementExecutor.java:279)
ksqldb-server    |      at io.confluent.ksql.rest.server.computation.InteractiveStatementExecutor.handleStatementWithTerminatedQueries(InteractiveStatementExecutor.java:212)
ksqldb-server    |      at io.confluent.ksql.rest.server.computation.InteractiveStatementExecutor.handleRestore(InteractiveStatementExecutor.java:135)
ksqldb-server    |      at io.confluent.ksql.rest.server.computation.CommandRunner.lambda$null$3(CommandRunner.java:276)
ksqldb-server    |      at io.confluent.ksql.util.RetryUtil.retryWithBackoff(RetryUtil.java:89)
ksqldb-server    |      at io.confluent.ksql.util.RetryUtil.retryWithBackoff(RetryUtil.java:60)
ksqldb-server    |      at io.confluent.ksql.util.RetryUtil.retryWithBackoff(RetryUtil.java:41)
ksqldb-server    |      at io.confluent.ksql.rest.server.computation.CommandRunner.lambda$processPriorCommands$4(CommandRunner.java:272)
ksqldb-server    |      at java.base/java.lang.Iterable.forEach(Iterable.java:75)
ksqldb-server    |      at io.confluent.ksql.rest.server.computation.CommandRunner.processPriorCommands(CommandRunner.java:269)
ksqldb-server    |      at io.confluent.ksql.rest.server.KsqlRestApplication.initialize(KsqlRestApplication.java:437)
ksqldb-server    |      at io.confluent.ksql.rest.server.KsqlRestApplication.startKsql(KsqlRestApplication.java:367)
ksqldb-server    |      at io.confluent.ksql.rest.server.KsqlRestApplication.startAsync(KsqlRestApplication.java:350)
ksqldb-server    |      at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:91)
ksqldb-server    |      at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:66)
```

**Additional context**
When I change `0.14.0` to `0.10.0` the example works.
