### ISSUE TITLE
show debug logs from custom connector on embedded connect

### ISSUE THREAD

**Issue by jfromaniello** [confluentinc/ksql#7005]
I am working on a source connector and I'd like to be able to read the debug logs. I've something like this like in several examples:

```java
private static final Logger log = LoggerFactory.getLogger(MyClass.class);
//...
log.debug("test");
```

I am running the container `confluentinc/ksqldb-server` as follows:

```
  ksqldb-server:
    image: confluentinc/ksqldb-server:0.14.0
    hostname: ksqldb-server
    container_name: ksqldb-server
    networks:
      - fusepoll-network
    depends_on:
      - kafka
    ports:
      - "8088:8088"
    volumes:
      - ./kafka/ksqldb/logs/log4j-custom.properties:/etc/ksqldb/log4j-rolling.properties
      - ./kafka/connect:/etc/kafka-connect/jars
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_EXTENSION_DIR: /extensions
      KSQL_CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_CONNECT_GROUP_ID: ksql-connect-cluster
      KSQL_CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      KSQL_CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      KSQL_CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars
      KSQL_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_CONFIG_STORAGE_TOPIC: "ksql-connect-configs"
      KSQL_CONNECT_OFFSET_STORAGE_TOPIC: "ksql-connect-offsets"
      KSQL_CONNECT_STATUS_STORAGE_TOPIC: "ksql-connect-statuses"
      KSQL_CONNECT_LOG4J_ROOT_LOGLEVEL: DEBUG
```

I tried chaging INFO to DEBUG in the  `log4j-rolling.properties`: `log4j.rootLogger=DEBUG, main`. I also tried adding 

```
log4j.category.com.mynamespace=DEBUG
```

sorry if this is too basic, I am fairly new to log4j. Thanks!
