### ISSUE TITLE
Monitor ksqlDB with JMX

### ISSUE THREAD

**Issue by Mall0c** [confluentinc/ksql#7247]
I have followed the instructions on this page: https://docs.ksqldb.io/en/latest/operate-and-deploy/monitoring/

This is my ksqldb-server part of docker-compose:

```
  ksqldb-server:
    image: confluentinc/ksqldb-server:0.15.0
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - kafka
      - schema-registry
      - kafka-connect
    ports:
      - "8088:8088"
      - "1099:1099"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka:29092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KSQL_KSQL_CONNECT_URL: http://kafka-connect:8083
      KSQL_KSQL_QUERY_PULL_METRICS_ENABLED: "true"
      KSQL_JMX_OPTS: > 
        -Djava.rmi.server.hostname=localhost
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=1099
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.rmi.port=1099
```

I have setup Prometheus in the same docker-compose file, and when I visit {prometheus-url}/targets, I see `Get "http://ksqldb-server:1099/metrics": EOF`

I have already tried plenty configurations during my research, including changing the -Djava.rmi.server.hostname either to the host's IP address or to ksqldb-server's container IP address, but none of them worked. Does anyone have a solution?

I have posted this question to https://stackoverflow.com/questions/66670242/monitor-ksqldb-with-jmx , but in order to raise some attention to it and to increase the probability someone responses, I have also posted this question here. I'm sorry in case thats not appropriate.
