### ISSUE TITLE
Materialized views are lost, when ksqldb restart

### ISSUE THREAD

**Issue by mogui** [confluentinc/ksql#7503]
I need to have a queryable Table, so I create a Materialized view with `CREATE  TABLE AS SELECT`.
everything works fine, but if ksqldb is restarted, The table created this way persist but is no more queryable.

It is an intended thing? Am I missing something or doing something wrong?
What I saw is that to maintain the table a persistent query is issued and a consumer with a query id is started, when ksqldb is restarted this consumer no longer is active.

I am using ksqldb  docker container.

**Comment by mjsax** [comment]
What version do you use? Would like to see if I can reproduce the issue. Atm, it sounds like a potential bug.

**Comment by mogui** [comment]
Hi @mjsax I am using this tag `confluentinc/ksqldb-server:0.17.0`, and run it with this configuration.
I alsoconfigured the volume cause i thought that was the problem but the it doesn't resolve the issue.


```
ksqldb:
    image: confluentinc/ksqldb-server:0.17.0
    hostname: ksqldb
    container_name: ksqldb
    links:
      - kafka
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_QUERY_PULL_TABLE_SCAN_ENABLED: "true"
      KSQL_KSQL_STREAMS_STATE_DIR: "/tmp/kafka-streams"
    volumes:
      - ./data/streams:/tmp/kafka-streams
```
