### ISSUE TITLE
ksql-migrations hangs without any output or logs

### ISSUE THREAD

**Issue by AdilHoumadi** [confluentinc/ksql#7567]
**Describe the bug**
ksql-migrations hangs without any output or logs

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL. (cp-ksqldb-server:6.1.1 or ksqldb-server:0.17.0)
2. Generate a new-migration `ksql-migrations new-project migrations/ http://remove-ksqldb-server:80`
3. Info or initialize are not given any feedback.
`./ksql-migrations --config-file migrations/ksql-migrations.properties info`
`./ksql-migrations --config-file migrations/ksql-migrations.properties initialize-metadata`

The server is up and running:
```
{
  "KsqlServerInfo": {
    "version": "0.17.0",
    "kafkaClusterId": "MQUKAhRDSAafKnnUe7Ibig",
    "ksqlServiceId": "example-server-id",
    "serverStatus": "RUNNING"
  }
}
```

**Expected behavior**
We should able to get details of the cluster via info command,
And we  be should able to init the migrations config (stream/table)

**Actual behaviour**
 The client just hangs. there is no output of the commands, 

```
./ksql-migrations --config-file migrations/ksql-migrations.properties initialize-metadata                                                                                                                                                ─╯
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
```

**Comment by jzaralim** [comment]
@AdilHoumadi Do you have the server logs? 

Also, is your docker compose file the same as #7560 but with ksqldb-server:0.17.0? The Confluent Platform docker compose uses a monitoring interceptor that does not ship with the ksqldb-server:0.17.0 image - try removing the KSQL_PRODUCER_INTERCEPTOR_CLASSES and KSQL_CONSUMER_INTERCEPTOR_CLASSES from the docker-compose file.

**Comment by AdilHoumadi** [comment]
@jzaralim, @vcrfxia 
We don't have this two env vars.
The server is up and running.

```
[2021-05-25 15:55:03,424] INFO [Consumer clientId=consumer-null-1, groupId=null] Subscribed to partition(s): _confluent-ksql-example-server-id_command_topic-0 (org.apache.kafka.clients.consumer.KafkaConsumer)
[2021-05-25 15:55:03,428] INFO [Consumer clientId=consumer-null-1, groupId=null] Seeking to EARLIEST offset of partition _confluent-ksql-example-server-id_command_topic-0 (org.apache.kafka.clients.consumer.internals.SubscriptionState)
[2021-05-25 15:55:03,529] INFO [Consumer clientId=consumer-null-1, groupId=null] Cluster ID: MQUKAhRDSAafKnnUe7Ibig (org.apache.kafka.clients.Metadata)
[2021-05-25 15:55:03,565] INFO [Consumer clientId=consumer-null-1, groupId=null] Resetting offset for partition _confluent-ksql-example-server-id_command_topic-0 to position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[kafka1.dev.pivotal.emea.kaas.3stripes.net:9093 (id: 1 rack: null)], epoch=11}}. (org.apache.kafka.clients.consumer.internals.SubscriptionState)
[2021-05-25 15:55:08,431] INFO Restoring previous state from 0 commands. (io.confluent.ksql.rest.server.computation.CommandRunner)
[2021-05-25 15:55:08,432] INFO Restarting 0 queries. (io.confluent.ksql.rest.server.computation.CommandRunner)
[2021-05-25 15:55:08,433] INFO Restore complete (io.confluent.ksql.rest.server.computation.CommandRunner)
[2021-05-25 15:55:08,435] INFO KSQL query monitor started. (io.confluent.ksql.engine.QueryMonitor)
[2021-05-25 15:55:08,436] INFO No customer ID configured -- falling back to id 'anonymous' (io.confluent.support.metrics.BaseSupportConfig)
[2021-05-25 15:55:08,436] WARN Enforcing customer ID 'anonymous' (io.confluent.support.metrics.PhoneHomeConfig)
[2021-05-25 15:55:08,437] WARN The version check feature of KSQL  is disabled. (io.confluent.ksql.version.metrics.KsqlVersionCheckerAgent)
[2021-05-25 15:55:08,437] INFO ksqlDB API server listening on http://0.0.0.0:8088 (io.confluent.ksql.rest.server.KsqlRestApplication)
[2021-05-25 15:55:08,437] INFO Server up and running (io.confluent.ksql.rest.server.KsqlServerMain)
```

**Comment by jzaralim** [comment]
@AdilHoumadi Is that everything in the logs? If it ends there then the server isn't even receiving any requests.

Do you mind sharing your docker-compose file? Also is `ksql-migrations new-project migrations/ http://remove-ksqldb-server:80 ` the exact command you used to create a new migration?

**Comment by AdilHoumadi** [comment]
@jzaralim,

It seems related to http client implemented to get the details of the cluster: `ServerVersionUtil.getServerInfo`
For the project, it's a deployment in K8S, here is some details:

```
    Image:          ksqldb-server:0.17.0
    ...
    Environment:
      KSQL_BOOTSTRAP_SERVERS:                             SSL://kafka1.dev.net:9093,SSL://kafka2.dev.net:9093,SSL://kafka3.dev.net:9093:9093
      KSQL_KSQL_SERVICE_ID:                               example-server-id
      KSQL_HEAP_OPTS:                                     -Xms512M -Xmx512M
      KSQL_SECURITY_PROTOCOL:                             SSL
      KSQL_SSL_KEYSTORE_LOCATION:                         /opt/certs/kafka/client/keystore.jks
      KSQL_SSL_KEYSTORE_PASSWORD:                         <set to the key 'password' in secret 'keystore.jks'>  Optional: false
      KSQL_SSL_KEY_PASSWORD:                              <set to the key 'password' in secret 'keystore.jks'>  Optional: false
      KSQL_SSL_TRUSTSTORE_LOCATION:                       /opt/certs/kafka/broker/truststore.jks
      KSQL_SSL_TRUSTSTORE_PASSWORD:                       <set to the key 'password' in secret 'truststore'>  Optional: false
      KSQL_KSQL_SCHEMA_REGISTRY_URL:                      https://schema-registry.dev.net/
      KSQL_KSQL_SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION:  /opt/certs/schema-registry/caroot.jks
      KSQL_KSQL_SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD:  <set to the key 'password' in secret 'caroot'>  Optional: false
      KSQL_LISTENERS:                                     http://0.0.0.0:8088
      KSQL_KSQL_INTERNAL_TOPIC_MIN_INSYNC_REPLICAS:       2
      KSQL_KSQL_INTERNAL_TOPIC_REPLICAS:                  3
      KSQL_KSQL_STREAMS_AUTO_OFFSET_RESET:                earliest
      JMX_PORT:                                           9999
      KSQL_OPTS:                                          -Dconfluent.support.metrics.enable=false
      KSQL_KSQL_EXTENSION_DIR:                            /opt/ksqldb-udfs
```

The commands:

```
./ksql-migrations initialize-metadata -c ./migrations/ksql-migrations.properties
./ksql-migrations info -c ./migrations/ksql-migrations.properties
```

I attached a remote debugger to the jar (ksqldb-tools-0.17.0.jar)
We see that the client hangs once we step the the next step:

Step 1 load config file and construct the http client:
![1](https://user-images.githubusercontent.com/462805/119610378-70171780-bdf9-11eb-9dd3-be94ce1b699a.png)

Step 2: remote call the server:
![2](https://user-images.githubusercontent.com/462805/119610576-bec4b180-bdf9-11eb-89a4-bf7d6b3e608b.png)

**Comment by AdilHoumadi** [comment]
I do have more details, deploying the service over **https** will allow the communication between the server and the client:

Here is the config:

```
ksql.server.url=https://remote-ksqldb-server.io:443
ssl.alpn=true

# ksqlDB server authentication configs:
ksql.migrations.stream.name=MIGRATION_EVENTS
ksql.migrations.table.name=MIGRATION_SCHEMA_VERSIONS
ksql.migrations.stream.topic.name=server_client_id_ksql_MIGRATION_EVENTS
ksql.migrations.table.topic.name=server_client_id_MIGRATION_SCHEMA_VERSIONS
ksql.migrations.topic.replicas=3
ksql.auth.basic.username=USERNAME
ksql.auth.basic.password=PASSWORD
```

my conclusion is that the low level implementation of the client does not allow the communication over http, you need to be in https, otherwise the client will hangs.

But I am still getting the same issue that I described in the other ticket regarding the compatibility of the API (#7560)

**Comment by jzaralim** [comment]
Thank you for the detailed response, this is very helpful! We'll look into that, do you have a copy of the `ksql-migrations.properties` file you used when you were using http? It would help us figure out what went wrong.


> But I am still getting the same issue that I described in the other ticket regarding the compatibility of the API (#7560)

Do you mean it's showing the same error message, even with an 0.17 server?

```
Failed to verify existence of migrations metadata stream 'MIGRATION_EVENTS'. Did you run `ksql-migrations initialize-metadata`? Error message: java.lang.IllegalStateException: Unexpected server response format. Response: {"@type":"sourceDescription","statementText":"describe MIGRATION_EVENTS;","sourceDescription":{"name":"MIGRATION_EVENTS","windowType":null,"readQueries":[{"queryString":"CREATE TABLE MIGRATION_SCHEMA_VERSIONS WITH (KAFKA_TOPIC='default_ksql_MIGRATION_SCHEMA_VERSIONS', PARTITIONS=1, REPLICAS=1) AS SELECT\n  MIGRATION_EVENTS.VERSION_KEY VERSION_KEY,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.VERSION) VERSION,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.NAME) NAME,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.STATE) STATE,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.CHECKSUM) CHECKSUM,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.STARTED_ON) STARTED_ON,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.COMPLETED_ON) COMPLETED_ON,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.PREVIOUS) PREVIOUS,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.ERROR_REASON) ERROR_REASON\nFROM MIGRATION_EVENTS MIGRATION_EVENTS\nGROUP BY MIGRATION_EVENTS.VERSION_KEY\nEMIT CHANGES;","sinks":["MIGRATION_SCHEMA_VERSIONS"],"sinkKafkaTopics":["default_ksql_MIGRATION_SCHEMA_VERSIONS"],"id":"CTAS_MIGRATION_SCHEMA_VERSIONS_3","statusCount":{"RUNNING":1},"queryType":"PERSISTENT","state":"RUNNING"}],"writeQueries":[],"fields":[{"name":"VERSION_KEY","schema":{"type":"STRING","fields":null,"memberSchema":null},"type":"KEY"},{"name":"VERSION","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"NAME","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"STATE","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"CHECKSUM","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"STARTED_ON","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"COMPLETED_ON","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"PREVIOUS","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"ERROR_REASON","schema":{"type":"STRING","fields":null,"memberSchema":null}}],"type":"STREAM","timestamp":"","statistics":"","errorStats":"","extended":false,"keyFormat":"KAFKA","valueFormat":"JSON","topic":"default_ksql_MIGRATION_EVENTS","partitions":0,"replication":0,"statement":"CREATE STREAM MIGRATION_EVENTS (VERSION_KEY STRING KEY, VERSION STRING, NAME STRING, STATE STRING, CHECKSUM STRING, STARTED_ON STRING, COMPLETED_ON STRING, PREVIOUS STRING, ERROR_REASON STRING) WITH (KAFKA_TOPIC='default_ksql_MIGRATION_EVENTS', KEY_FORMAT='KAFKA', PARTITIONS=1, REPLICAS=1, VALUE_FORMAT='JSON');","queryOffsetSummaries":[]},"warnings":[]}
```

**Comment by AdilHoumadi** [comment]
@jzaralim, indeed switch to https the client does not hang anymore but it's giving the error that you mentioned:
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Failed to verify existence of migrations metadata stream 'MIGRATION_EVENTS'. Did you run `ksql-migrations initialize-metadata`? Error message: java.lang.IllegalStateException: Unexpected server response format. Response: {"@type":"sourceDescription","statementText":"describe MIGRATION_EVENTS;","sourceDescription":{"name":"MIGRATION_EVENTS","windowType":null,"readQueries":[{"queryString":"CREATE TABLE MIGRATION_SCHEMA_VERSIONS WITH (KAFKA_TOPIC='server_client_idMIGRATION_SCHEMA_VERSIONS', PARTITIONS=1, REPLICAS=3) AS SELECT\n  MIGRATION_EVENTS.VERSION_KEY VERSION_KEY,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.VERSION) VERSION,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.NAME) NAME,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.STATE) STATE,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.CHECKSUM) CHECKSUM,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.STARTED_ON) STARTED_ON,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.COMPLETED_ON) COMPLETED_ON,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.PREVIOUS) PREVIOUS,\n  LATEST_BY_OFFSET(MIGRATION_EVENTS.ERROR_REASON) ERROR_REASON\nFROM MIGRATION_EVENTS MIGRATION_EVENTS\nGROUP BY MIGRATION_EVENTS.VERSION_KEY\nEMIT CHANGES;","sinks":["MIGRATION_SCHEMA_VERSIONS"],"sinkKafkaTopics":["server_client_idMIGRATION_SCHEMA_VERSIONS"],"id":"CTAS_MIGRATION_SCHEMA_VERSIONS_1","statusCount":{"RUNNING":1},"queryType":"PERSISTENT","state":"RUNNING"}],"writeQueries":[],"fields":[{"name":"VERSION_KEY","schema":{"type":"STRING","fields":null,"memberSchema":null},"type":"KEY"},{"name":"VERSION","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"NAME","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"STATE","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"CHECKSUM","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"STARTED_ON","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"COMPLETED_ON","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"PREVIOUS","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"ERROR_REASON","schema":{"type":"STRING","fields":null,"memberSchema":null}}],"type":"STREAM","timestamp":"","statistics":"","errorStats":"","extended":false,"keyFormat":"KAFKA","valueFormat":"JSON","topic":"server_client_idMIGRATION_EVENTS","partitions":0,"replication":0,"statement":"CREATE STREAM MIGRATION_EVENTS (VERSION_KEY STRING KEY, VERSION STRING, NAME STRING, STATE STRING, CHECKSUM STRING, STARTED_ON STRING, COMPLETED_ON STRING, PREVIOUS STRING, ERROR_REASON STRING) WITH (KAFKA_TOPIC='server_client_idMIGRATION_EVENTS', KEY_FORMAT='KAFKA', PARTITIONS=1, REPLICAS=3, VALUE_FORMAT='JSON');","queryOffsetSummaries":[]},"warnings":[]}
Execution time: 1.4420 seconds
```

For the config, it's the same: the only diff is: (http instead of https and this alpn param which is not needed in http mode)


```
ksql.server.url=http://remote-ksqldb-server.io:80

# ksqlDB server authentication configs:
ksql.migrations.stream.name=MIGRATION_EVENTS
ksql.migrations.table.name=MIGRATION_SCHEMA_VERSIONS
ksql.migrations.stream.topic.name=server_client_id_ksql_MIGRATION_EVENTS
ksql.migrations.table.topic.name=server_client_id_MIGRATION_SCHEMA_VERSIONS
ksql.migrations.topic.replicas=3
ksql.auth.basic.username=USERNAME
ksql.auth.basic.password=PASSWORD
```

**Comment by jzaralim** [comment]
Thanks @AdilHoumadi, I'll test that out sometime.

I also just noticed this now, but 0.17 is not included in cp-ksqldb-server:6.1.1. That's coming in 6.2.0.

Do you mind running `curl -u <username>:<password> https://remote-ksqldb-server.io:443/info` just to make sure it's the right version? It's very concerning if we're getting that error response in 0.17.

**Comment by AdilHoumadi** [comment]
i have the issue for both versions.
this the answer of curl.

```
{
  "KsqlServerInfo": {
    "version": "0.17.0",
    "kafkaClusterId": "MQUKAhRDSAafKnnUe7Ibig",
    "ksqlServiceId": "example-server-id",
    "serverStatus": "RUNNING"
  }
}
```

```
{
  "KsqlServerInfo": {
    "version": "6.1.1",
    "kafkaClusterId": "MQUKAhRDSAafKnnUe7Ibig",
    "ksqlServiceId": "example-server-id",
    "serverStatus": "RUNNING"
  }
}
```

**Comment by jzaralim** [comment]
Hi @AdilHoumadi , I was not able to replicate this. For reference, the docker-compose file I was using is

```
---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:6.1.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  schema-registry:
    image: confluentinc/cp-schema-registry:6.1.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  connect:
    image: cnfldemos/cp-server-connect-datagen:0.4.0-6.1.0
    hostname: connect
    container_name: connect
    depends_on:
      - broker
      - schema-registry
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      # CLASSPATH required due to CC-2422
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-6.1.1.jar
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.1.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker
      - schema-registry
      - connect
      - ksqldb-server
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.17.0
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - broker
      - connect
    ports:
      - "8088:8088"
    volumes:
      - ./files:/home/appuser/
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_BOOTSTRAP_SERVERS: "broker:29092"
      KSQL_HOST_NAME: ksqldb-server
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_KSQL_CONNECT_URL: "http://connect:8083"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: 'true'
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: 'true'
      KSQL_AUTHENTICATION_METHOD: BASIC
      KSQL_AUTHENTICATION_REALM: KsqlServer-Props
      KSQL_AUTHENTICATION_ROLES: admin,developer
      KSQL_CLASSPATH: /home/appuser/jetty-jaas-9.4.24.v20191120.jar:/usr/share/java/ksqldb-server/*
      KSQL_OPTS: "-Djava.security.auth.login.config=/home/appuser/jaas_config.file"

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.17.0
    container_name: ksqldb-cli
    depends_on:
      - broker
      - connect
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true

  ksql-datagen:
    image: confluentinc/ksqldb-examples:6.1.1
    hostname: ksql-datagen
    container_name: ksql-datagen
    depends_on:
      - ksqldb-server
      - broker
      - schema-registry
      - connect
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                       cub kafka-ready -b broker:29092 1 40 && \
                       echo Waiting for Confluent Schema Registry to be ready... && \
                       cub sr-ready schema-registry 8081 40 && \
                       echo Waiting a few seconds for topic creation to finish... && \
                       sleep 11 && \
                       tail -f /dev/null'"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      STREAMS_BOOTSTRAP_SERVERS: broker:29092
      STREAMS_SCHEMA_REGISTRY_HOST: schema-registry
      STREAMS_SCHEMA_REGISTRY_PORT: 8081

  rest-proxy:
    image: confluentinc/cp-kafka-rest:6.1.1
    depends_on:
      - broker
      - schema-registry
    ports:
      - 8082:8082
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:29092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'

  ksqldb-migrations:
    image: confluentinc/ksqldb-cli:0.17.0
    container_name: ksqldb-migrations
    hostname: ksqldb-migrations
    depends_on:
      - broker
      - ksqldb-server
    tty: true
    volumes:
      - "./migrations:/share/migrations"
    command: "sleep infinity"
```

and the migration config file is

```
ksql.server.url=http://ksqldb-server:8088

# Migrations metadata configs:
# ksql.migrations.stream.name=MIGRATION_EVENTS
# ksql.migrations.table.name=MIGRATION_SCHEMA_VERSIONS
# ksql.migrations.stream.topic.name=ksql-service-idksql_MIGRATION_EVENTS
# ksql.migrations.table.topic.name=ksql-service-idksql_MIGRATION_SCHEMA_VERSIONS
# ksql.migrations.topic.replicas=1

# TLS configs:
# ssl.truststore.location=
# ssl.truststore.password=
# ssl.keystore.location=
# ssl.keystore.password=
# ssl.key.password=
# ssl.key.alias=
# ssl.alpn=false
# ssl.verify.host=true

# ksqlDB server authentication configs:
ksql.auth.basic.username=fred
ksql.auth.basic.password=letmein
```

Please let us know if you ever figure out what went wrong, I would like to know as well.
