### ISSUE TITLE
docker-entrypoint - generating streams on startup

### ISSUE THREAD

**Issue by flashpixx** [confluentinc/ksql#8101]
I just use this configuration (docker-compose):

```
version: "3.8"
volumes:
    kafka_data:

services:

    zookeeper:
      restart: always
      image: bitnami/zookeeper:3.7
      ports:
        - ${EXPOSE_PORT_ZOOKEEPER:-2181}:2181
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes


    kafka:
      restart: always
      image: bitnami/kafka:2.8.0
      ports:
        - ${EXPOSE_PORT_KAFKA:-9092}:9092
      volumes:
        - kafka_data:/bitnami/kafka
      environment:
        KAFKA_BROKER_ID: 1
        ALLOW_PLAINTEXT_LISTENER: "yes"
        KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
        KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CFG_LISTENERS: CLIENT://:9092
        KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT
        KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9092
      depends_on:
        - zookeeper


    ksql:
      restart: always
      image: confluentinc/ksqldb-server:0.20.0
      ports:
        - ${EXPOSE_PORT_KSQLDB:-8088}:8088
      environment:
        KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
        KSQL_LISTENERS: "http://0.0.0.0:8088/"
        KSQL_KSQL_SERVICE_ID: "sql-"
      volumes: 
       # ===== how can I make this line work ====
        - ./assets/ksql/:/opt/queries
```

I would like to get the possibility if ksql-server start it create my Kafka steams, so e.g. on Postgres I have got a directory in my container `/docker-entrypoint` which can be mounted and if I place some SQL files it execute the files and create the database structure. 

How can I make this work with ksql-server?

Thanks a lot
