### ISSUE TITLE
How to consume data in KSqlDb docker version using Avro format?

### ISSUE THREAD

**Issue by jdang67** [confluentinc/ksql#8131]
Hi Everyone,

I searched but could not find any example to use Avro format from SchemaRegistry with KSqlDb.
Since there is no documentation or at least I could not find one, I just guessing the variable names 
and put  into the docker-compose as follow: 
```json
KSQL_STREAMS_DEFAULT_KEY_SERDE: org.apache.kafka.common.serialization.stringdeserializer
KSQL_STREAMS_DEFAULT_VALUE_SERDE: io.confluent.kafka.streams.serdes.avro.specificavroserde
```
So far, when I try to read the data from a topic, I see the binary as below.
What do I need to do in order to see data in Avro format?

Thanks,
Jdang

``` json
rowtime: 2021/09/14 21:17:09.028 Z, key: [3@3906650795381503024/-], value: \x00\x00\x00\x00\x15\x02\x02\x02\x00\x02\x12367638640\x02\x020\x02\x00\x02\x00\x02\x00\x00\x00\x00\x02\x02\x02\xBDC\xB6\xC2\x02EX\xEDA\x022\x02\xFE\x07\x02\x12\x02\x00\x02\x02\x02\x8E\x82\x0A\x02\x06OII\x00\x02^!AIVDM,1,1,,B,15NVpL0P00qNm4t@vNcA0gvB2D27,0*3D\x02\xA8\xC5\x88\x94\x0C, partition: 13
```
And here is my docker-compose.yaml
``` yaml
version: "3.9"
services:
  ksqldb-server:
    image: confluentinc/ksqldb-server
    hostname: ksqldb-server
    container_name: ksqldb-server
    ports:
       - "8088:8088"
    volumes:
      - ./Dev:/home/appuser/
    environment:
      #KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: "bootstrap-server:port#"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "my-schema-registry:port#"
      KSQL_SSL_KEYSTORE_LOCATION: "client.keystore.p12"
      KSQL_SSL_KEYSTORE_PASSWORD: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      KSQL_SSL_TRUSTSTORE_LOCATION: "client.truststore.jks"
      KSQL_SSL_TRUSTSTORE_PASSWORD: "xxxxxxxxxxxxxxxxxxxxxxxx"
      KSQL_STREAMS_STATE_DIR: ./KSqlState
      KSQL_SECURITY_PROTOCOL: SSL
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_SERVICE_ID: my-ksqldb
      KSQL_LOG4J_ROOT_LOGLEVEL: "INFO"
      KSQL_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      KSQL_STREAMS_AUTO_OFFSET_RESET: earliest
      KSQL_STREAMS_DEFAULT_KEY_SERDE: org.apache.kafka.common.serialization.stringdeserializer
      KSQL_STREAMS_DEFAULT_VALUE_SERDE: io.confluent.kafka.streams.serdes.avro.specificavroserde
  # Access the cli by running:
  # > docker-compose exec ksqldb-cli  ksql http://ksqldb-server:8088
  ksqldb-cli:
    image: confluentinc/ksqldb-cli
    container_name: ksqldb-cli
    depends_on:
      - ksqldb-server
    tty: true
    entrypoint: 
      - /bin/sh
```
