### ISSUE TITLE
where is the dockerfile of confluentinc/ksqldb-server ?

### ISSUE THREAD

**Issue by raphaelauv** [confluentinc/ksql#8930]
this page https://hub.docker.com/r/confluentinc/ksqldb-server

do not  give the link to the dockerfile of `ksqldb-server`

do you know where is the dockerfile? thanks

**Comment by raphaelauv** [comment]
the image confluentinc/ksqldb-server is not build with this repo https://github.com/confluentinc/ksql-images

since I can't find the files of the folder `include/etc/confluent/docker/*` inside the image

**Comment by raphaelauv** [comment]
Since I want custom LOG4J ( what is impossible with https://hub.docker.com/r/confluentinc/ksqldb-server )

I had to create a custom image

```dockerfile
FROM confluentinc/ksqldb-server:0.24.0

ADD --chown=appuser:appuser run /usr/bin/docker/run
ADD --chown=appuser:appuser log4j.properties.template /etc/confluent/docker/log4j.properties.template

RUN chmod +x /usr/bin/docker/run
```

and add the this line to the file `run`

```
dub template "/etc/confluent/docker/log4j.properties.template" "/etc/ksqldb/log4j.properties"
```

**Comment by Diyaa1** [comment]
this really confused me when following up this page https://docs.ksqldb.io/en/latest/reference/processing-log/.

below configurations didn't work for me when using ksqldb-server image
```
environment:
    # --- ksqlDB Server log config ---
    KSQL_LOG4J_ROOT_LOGLEVEL: "ERROR"
    KSQL_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
    # --- ksqlDB processing log config ---
    KSQL_LOG4J_PROCESSING_LOG_BROKERLIST: kafka:29092
    KSQL_LOG4J_PROCESSING_LOG_TOPIC: <ksql-processing-log-topic-name>
    KSQL_KSQL_LOGGING_PROCESSING_TOPIC_NAME: <ksql-processing-log-topic-name>
    KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
    KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
```
