### ISSUE TITLE
Problem writing to topics with ksqldb and Kafka ACLs 

### ISSUE THREAD

**Issue by aachenmax** [confluentinc/ksql#9718]
Hello everybody, I'm currently testing ksqldb-server and have some issues connecting ksqldb to a managed Kafka cluster (MSK) that uses ACLs. Specifically, there seems to be a problem when writing to topics with ksqldb (INSERT).

For the setup, I followed the guidelines [here](https://docs.ksqldb.io/en/latest/operate-and-deploy/installation/server-config/security/#configure-authorization-of-ksqldb-with-kafka-acls) to configure the authorization required for ksqldb. Below is an excerpt from the current ACLs I'm using. The `<ksql.service.id>` is set to "test" in ksqldb-server and we prefix the output topics, e.g. `ksql.output.topic.name.prefix` is set to "private.test." (see also ksqldb configuration below):

### ACLs:
```
test.ksqldb-user:
    allow-describe-configs-cluster:
      name: "kafka-cluster"
      type: CLUSTER
      pattern: LITERAL
      host: "*"
      operation: DESCRIBE_CONFIGS
      permission: ALLOW
    allow-describe-cluster:
      name: "kafka-cluster"
      type: CLUSTER
      pattern: LITERAL
      host: "*"
      operation: DESCRIBE
      permission: ALLOW
    allow-all-ksql-groups:
      name: "_confluent-ksql-test"
      type: GROUP
      pattern: PREFIXED
      host: "*"
      operation: ALL
      permission: ALLOW
    allow-all-ksql-topics:
      name: "_confluent-ksql-test"
      type: TOPIC
      pattern: PREFIXED
      host: "*"
      operation: ALL
      permission: ALLOW
    allow-all-private-topics:
      name: private.test
      type: TOPIC
      pattern: PREFIXED
      host: "*"
      operation: ALL
      permission: ALLOW
    allow-all-private-groups:
      name: private.test
      type: GROUP
      pattern: PREFIXED
      host: "*"
      operation: ALL
      permission: ALLOW
    allow-read-all-groups:
      name: "*"
      type: GROUP
      pattern: LITERAL
      host: "*"
      operation: READ
      permission: ALLOW
    allow-describe-all-topics:
      name: "*"
      type: TOPIC
      pattern: LITERAL
      host: "*"
      operation: DESCRIBE
      permission: ALLOW
    allow-describe-all-groups:
      name: "*"
      type: GROUP
      pattern: LITERAL
      host: "*"
      operation: DESCRIBE
      permission: ALLOW
    allow-describe-configs-all-topics:
      name: "*"
      type: TOPIC
      pattern: LITERAL
      host: "*"
      operation: DESCRIBE_CONFIGS
      permission: ALLOW
    allow-describe-configs-all-groups:
      name: "*"
      type: GROUP
      pattern: LITERAL
      host: "*"
      operation: DESCRIBE_CONFIGS
      permission: ALLOW
    allow-describe-transactional-id:
      name: "test"
      type: TRANSACTIONAL_ID
      pattern: LITERAL
      host: "*"
      operation: DESCRIBE
      permission: ALLOW
    allow-write-transactional-id:
      name: "test"
      type: TRANSACTIONAL_ID
      pattern: LITERAL
      host: "*"
      operation: WRITE
      permission: ALLOW
```
### ksqldb Configuration

```
image: confluentinc/cp-ksqldb-server
imageTag: 7.3.0

...

ksql:
  headless: false

...

configurationOverrides: 
  "security.protocol": "SASL_SSL" 
  "sasl.mechanism": "SCRAM-SHA-512"
  "ksql.output.topic.name.prefix": "private.test."
  "sasl.jaas.config": "org.apache.kafka.common.security.scram.ScramLoginModule required username='test.ksqldb-user' password='######';"
  "ksql.service.id": "test"
```

This configuration seems to work fine and ksqldb starts without any issues. The command topic is successfully created and also filled with data. Using ksql-cli I can also successfully create a stream:

```
ksql> CREATE STREAM test_stream (key VARCHAR KEY, message VARCHAR) WITH (kafka_topic='private.test.test_stream', value_format='JSON', partitions=1);

 Message        
----------------
 Stream created 
----------------
```

However, when I try to insert data into the stream, I get the following error:

```
ksql> INSERT INTO test_stream (key, message) VALUES ('testKey', 'Hello World!');

Failed to insert values into 'TEST_STREAM'.
Caused by: Authorization denied to Write on topic(s):
	[private.test.test_stream]. Caused by: The producer is not authorized
	to do idempotent sends. Check that you have write permissions to the specified
	topic, and disable idempotent sends by setting 'enable.idempotent=false'  if
	necessary.
```

I tried the suggestion and set `'enable.idempotent=false'` in the configurationOverrides. This now allows inserting data into the existing stream, however, new streams cannot be created anymore:

```
ksql> CREATE STREAM test_stream2 (key VARCHAR KEY, message VARCHAR) WITH (kafka_topic='private.test.test_stream2', value_format='JSON', partitions=1);

Cannot set a transactional.id without also enabling idempotence.
```

To double check, whether this is another authorization issue, I also tried a plain kafka producer client using `confluent_kafka` in Python (https://github.com/confluentinc/confluent-kafka-python) and the same credentials as above to write data into the topic. This also works without any problems. 

It would be great to get some hints on maybe missing configuration or ACLs to get ksqldb to work as expected or to know if others have encountered similar issues.
